/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FashionShop;

import java.io.IOException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author User
 */
public class MenFashion extends javax.swing.JFrame {

   
    
    /**
     * Creates new form MenFashion
     */
    public MenFashion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel = new javax.swing.JPanel();
        MenFashion = new javax.swing.JLabel();
        accessories = new javax.swing.JLabel();
        clothings = new javax.swing.JLabel();
        shoes = new javax.swing.JLabel();
        logo2 = new javax.swing.JLabel();
        logo1 = new javax.swing.JLabel();
        bagsandwallets = new javax.swing.JLabel();
        hatsandcaps = new javax.swing.JLabel();
        glasses = new javax.swing.JLabel();
        watches = new javax.swing.JLabel();
        tshirts = new javax.swing.JLabel();
        hoodies = new javax.swing.JLabel();
        jeansandtrousers = new javax.swing.JLabel();
        sneakersandsportshoes = new javax.swing.JLabel();
        boots = new javax.swing.JLabel();
        slippers = new javax.swing.JLabel();
        socks = new javax.swing.JLabel();
        back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel.setBackground(new java.awt.Color(36, 47, 65));

        MenFashion.setFont(new java.awt.Font("Sitka Text", 3, 24)); // NOI18N
        MenFashion.setForeground(new java.awt.Color(255, 255, 255));
        MenFashion.setText("Men's Fashion");

        accessories.setFont(new java.awt.Font("Sitka Text", 3, 16)); // NOI18N
        accessories.setForeground(new java.awt.Color(255, 255, 255));
        accessories.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        accessories.setText("Accessories");

        clothings.setFont(new java.awt.Font("Sitka Text", 3, 16)); // NOI18N
        clothings.setForeground(new java.awt.Color(255, 255, 255));
        clothings.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        clothings.setText("Clothings");

        shoes.setFont(new java.awt.Font("Sitka Text", 3, 16)); // NOI18N
        shoes.setForeground(new java.awt.Color(255, 255, 255));
        shoes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        shoes.setText("Shoes");

        logo2.setIcon(new javax.swing.ImageIcon("D:\\Photo\\men1.png")); // NOI18N

        logo1.setIcon(new javax.swing.ImageIcon("D:\\Photo\\men.png")); // NOI18N

        bagsandwallets.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        bagsandwallets.setForeground(new java.awt.Color(255, 255, 255));
        bagsandwallets.setText("Bags & Wallets");
        bagsandwallets.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bagsandwalletsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bagsandwalletsMouseExited(evt);
            }
        });

        hatsandcaps.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        hatsandcaps.setForeground(new java.awt.Color(255, 255, 255));
        hatsandcaps.setText("Hats & Caps");
        hatsandcaps.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                hatsandcapsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                hatsandcapsMouseExited(evt);
            }
        });

        glasses.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        glasses.setForeground(new java.awt.Color(255, 255, 255));
        glasses.setText("Glasses");
        glasses.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                glassesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                glassesMouseExited(evt);
            }
        });

        watches.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        watches.setForeground(new java.awt.Color(255, 255, 255));
        watches.setText("Watches");
        watches.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                watchesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                watchesMouseExited(evt);
            }
        });

        tshirts.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        tshirts.setForeground(new java.awt.Color(255, 255, 255));
        tshirts.setText("T-shirts");
        tshirts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tshirtsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tshirtsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tshirtsMouseExited(evt);
            }
        });

        hoodies.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        hoodies.setForeground(new java.awt.Color(255, 255, 255));
        hoodies.setText("Hoodies");
        hoodies.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                hoodiesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                hoodiesMouseExited(evt);
            }
        });

        jeansandtrousers.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jeansandtrousers.setForeground(new java.awt.Color(255, 255, 255));
        jeansandtrousers.setText("Jeans & Trousers");
        jeansandtrousers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jeansandtrousersMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jeansandtrousersMouseExited(evt);
            }
        });

        sneakersandsportshoes.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        sneakersandsportshoes.setForeground(new java.awt.Color(255, 255, 255));
        sneakersandsportshoes.setText("Sneakers & Sport Shoes");
        sneakersandsportshoes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sneakersandsportshoesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sneakersandsportshoesMouseExited(evt);
            }
        });

        boots.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        boots.setForeground(new java.awt.Color(255, 255, 255));
        boots.setText("Boots");
        boots.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bootsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bootsMouseExited(evt);
            }
        });

        slippers.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        slippers.setForeground(new java.awt.Color(255, 255, 255));
        slippers.setText("Slippers");
        slippers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                slippersMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                slippersMouseExited(evt);
            }
        });

        socks.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        socks.setForeground(new java.awt.Color(255, 255, 255));
        socks.setText("Socks");
        socks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                socksMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                socksMouseExited(evt);
            }
        });

        back.setBackground(new java.awt.Color(36, 47, 65));
        back.setFont(new java.awt.Font("Sitka Text", 1, 12)); // NOI18N
        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setText("<<Back");
        back.setBorder(null);
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(logo1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(MenFashion)
                .addGap(18, 18, 18)
                .addComponent(logo2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelLayout.createSequentialGroup()
                                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(accessories)
                                    .addComponent(bagsandwallets)
                                    .addComponent(hatsandcaps)
                                    .addComponent(glasses))
                                .addGap(72, 72, 72)
                                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(clothings)
                                    .addComponent(tshirts)
                                    .addComponent(hoodies)
                                    .addComponent(jeansandtrousers)))
                            .addComponent(watches))
                        .addGap(59, 59, 59)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(socks)
                            .addComponent(slippers)
                            .addComponent(boots)
                            .addComponent(sneakersandsportshoes)
                            .addComponent(shoes))))
                .addGap(50, 50, 50))
        );
        jPanelLayout.setVerticalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logo2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MenFashion)
                    .addComponent(logo1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(clothings, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(accessories, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(shoes, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bagsandwallets, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tshirts, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sneakersandsportshoes, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hatsandcaps, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hoodies, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boots, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(glasses, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jeansandtrousers, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(slippers, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(watches, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(socks, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bagsandwalletsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bagsandwalletsMouseEntered
        evt.getComponent().setForeground(java.awt.Color.BLACK);
    }//GEN-LAST:event_bagsandwalletsMouseEntered

    private void bagsandwalletsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bagsandwalletsMouseExited
        evt.getComponent().setForeground(java.awt.Color.WHITE);
    }//GEN-LAST:event_bagsandwalletsMouseExited

    private void hatsandcapsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hatsandcapsMouseEntered
        evt.getComponent().setForeground(java.awt.Color.BLACK);
    }//GEN-LAST:event_hatsandcapsMouseEntered

    private void hatsandcapsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hatsandcapsMouseExited
        evt.getComponent().setForeground(java.awt.Color.WHITE);
    }//GEN-LAST:event_hatsandcapsMouseExited

    private void glassesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_glassesMouseEntered
        evt.getComponent().setForeground(java.awt.Color.BLACK);
    }//GEN-LAST:event_glassesMouseEntered

    private void glassesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_glassesMouseExited
        evt.getComponent().setForeground(java.awt.Color.WHITE);
    }//GEN-LAST:event_glassesMouseExited

    private void watchesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_watchesMouseEntered
        evt.getComponent().setForeground(java.awt.Color.BLACK);
    }//GEN-LAST:event_watchesMouseEntered

    private void watchesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_watchesMouseExited
        evt.getComponent().setForeground(java.awt.Color.WHITE);
    }//GEN-LAST:event_watchesMouseExited

    private void tshirtsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tshirtsMouseEntered
        evt.getComponent().setForeground(java.awt.Color.BLACK);
    }//GEN-LAST:event_tshirtsMouseEntered

    private void tshirtsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tshirtsMouseExited
        evt.getComponent().setForeground(java.awt.Color.WHITE);
    }//GEN-LAST:event_tshirtsMouseExited

    private void hoodiesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hoodiesMouseEntered
        evt.getComponent().setForeground(java.awt.Color.BLACK);
    }//GEN-LAST:event_hoodiesMouseEntered

    private void hoodiesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hoodiesMouseExited
       evt.getComponent().setForeground(java.awt.Color.WHITE);
    }//GEN-LAST:event_hoodiesMouseExited

    private void jeansandtrousersMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jeansandtrousersMouseEntered
        evt.getComponent().setForeground(java.awt.Color.BLACK);
    }//GEN-LAST:event_jeansandtrousersMouseEntered

    private void jeansandtrousersMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jeansandtrousersMouseExited
        evt.getComponent().setForeground(java.awt.Color.WHITE);
    }//GEN-LAST:event_jeansandtrousersMouseExited

    private void sneakersandsportshoesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sneakersandsportshoesMouseEntered
        evt.getComponent().setForeground(java.awt.Color.BLACK);
    }//GEN-LAST:event_sneakersandsportshoesMouseEntered

    private void sneakersandsportshoesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sneakersandsportshoesMouseExited
        evt.getComponent().setForeground(java.awt.Color.WHITE);
    }//GEN-LAST:event_sneakersandsportshoesMouseExited

    private void bootsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bootsMouseEntered
        evt.getComponent().setForeground(java.awt.Color.BLACK);
    }//GEN-LAST:event_bootsMouseEntered

    private void bootsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bootsMouseExited
        evt.getComponent().setForeground(java.awt.Color.WHITE);
    }//GEN-LAST:event_bootsMouseExited

    private void slippersMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_slippersMouseEntered
        evt.getComponent().setForeground(java.awt.Color.BLACK);
    }//GEN-LAST:event_slippersMouseEntered

    private void slippersMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_slippersMouseExited
        evt.getComponent().setForeground(java.awt.Color.WHITE);
    }//GEN-LAST:event_slippersMouseExited

    private void socksMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_socksMouseEntered
        evt.getComponent().setForeground(java.awt.Color.BLACK);
    }//GEN-LAST:event_socksMouseEntered

    private void socksMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_socksMouseExited
        evt.getComponent().setForeground(java.awt.Color.WHITE);
    }//GEN-LAST:event_socksMouseExited

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        
        ChooseGender p2 = new ChooseGender();
        p2.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_backActionPerformed

    private void tshirtsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tshirtsMouseClicked
        
        try {
            new BrandsCustom().setVisible(true);
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(MenFashion.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(MenFashion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tshirtsMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenFashion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenFashion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenFashion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenFashion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenFashion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel MenFashion;
    private javax.swing.JLabel accessories;
    private javax.swing.JButton back;
    private javax.swing.JLabel bagsandwallets;
    private javax.swing.JLabel boots;
    private javax.swing.JLabel clothings;
    private javax.swing.JLabel glasses;
    private javax.swing.JLabel hatsandcaps;
    private javax.swing.JLabel hoodies;
    private javax.swing.JPanel jPanel;
    private javax.swing.JLabel jeansandtrousers;
    private javax.swing.JLabel logo1;
    private javax.swing.JLabel logo2;
    private javax.swing.JLabel shoes;
    private javax.swing.JLabel slippers;
    private javax.swing.JLabel sneakersandsportshoes;
    private javax.swing.JLabel socks;
    private javax.swing.JLabel tshirts;
    private javax.swing.JLabel watches;
    // End of variables declaration//GEN-END:variables
}
