/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FashionShop;

/**
 *
 * @author User
 */
public class WomenFashion extends javax.swing.JFrame {

    /**
     * Creates new form WomenFashion
     */
    public WomenFashion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel = new javax.swing.JPanel();
        accessories = new javax.swing.JLabel();
        bagsandpurses = new javax.swing.JLabel();
        glasses = new javax.swing.JLabel();
        scarvesandcaps = new javax.swing.JLabel();
        watches = new javax.swing.JLabel();
        clothings = new javax.swing.JLabel();
        shoes = new javax.swing.JLabel();
        dresses = new javax.swing.JLabel();
        jeansandtrousers = new javax.swing.JLabel();
        tshirtsandblouses = new javax.swing.JLabel();
        hoodies = new javax.swing.JLabel();
        socks = new javax.swing.JLabel();
        shorts = new javax.swing.JLabel();
        skirts = new javax.swing.JLabel();
        heels = new javax.swing.JLabel();
        slippers = new javax.swing.JLabel();
        sneakers = new javax.swing.JLabel();
        WomenFashion = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel.setBackground(new java.awt.Color(255, 153, 255));

        accessories.setFont(new java.awt.Font("Sitka Text", 3, 16)); // NOI18N
        accessories.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        accessories.setText("Accessories");

        bagsandpurses.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        bagsandpurses.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bagsandpurses.setText("Bags & Purses");
        bagsandpurses.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bagsandpursesLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bagsandpursesLabelMouseExit(evt);
            }
        });

        glasses.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        glasses.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        glasses.setText("Glasses");
        glasses.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                glassesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                glassesMouseExited(evt);
            }
        });

        scarvesandcaps.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        scarvesandcaps.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        scarvesandcaps.setText("Scarves & Caps");
        scarvesandcaps.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                scarvesandcapsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                scarvesandcapsMouseExited(evt);
            }
        });

        watches.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        watches.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        watches.setText("Watches");
        watches.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                watchesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                watchesMouseExited(evt);
            }
        });

        clothings.setFont(new java.awt.Font("Sitka Text", 3, 16)); // NOI18N
        clothings.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        clothings.setText("Clothings");

        shoes.setFont(new java.awt.Font("Sitka Text", 3, 16)); // NOI18N
        shoes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        shoes.setText("Shoes");

        dresses.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        dresses.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dresses.setText("Dresses");
        dresses.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dressesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                dressesMouseExited(evt);
            }
        });

        jeansandtrousers.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jeansandtrousers.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jeansandtrousers.setText("Jeans & Trousers");
        jeansandtrousers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jeansandtrousersMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jeansandtrousersMouseExited(evt);
            }
        });

        tshirtsandblouses.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        tshirtsandblouses.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tshirtsandblouses.setText("T-shirts & Blouses");
        tshirtsandblouses.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tshirtsandblousesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tshirtsandblousesMouseExited(evt);
            }
        });

        hoodies.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        hoodies.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hoodies.setText("Hoodies");
        hoodies.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                hoodiesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                hoodiesMouseExited(evt);
            }
        });

        socks.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        socks.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        socks.setText("Socks");
        socks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                socksMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                socksMouseExited(evt);
            }
        });

        shorts.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        shorts.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        shorts.setText("Shorts");
        shorts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                shortsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                shortsMouseExited(evt);
            }
        });

        skirts.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        skirts.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        skirts.setText("Skirts");
        skirts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                skirtsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                skirtsMouseExited(evt);
            }
        });

        heels.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        heels.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        heels.setText("Heels");
        heels.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                heelsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                heelsMouseExited(evt);
            }
        });

        slippers.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        slippers.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        slippers.setText("Slippers");
        slippers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                slippersMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                slippersMouseExited(evt);
            }
        });

        sneakers.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        sneakers.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sneakers.setText("Sneakers & Sport Shoes");
        sneakers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sneakersMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sneakersMouseExited(evt);
            }
        });

        WomenFashion.setFont(new java.awt.Font("Sitka Text", 3, 24)); // NOI18N
        WomenFashion.setText("Women's Fashion");

        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\Photo\\women.png")); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon("D:\\Photo\\women1.png")); // NOI18N

        back.setBackground(new java.awt.Color(255, 153, 255));
        back.setFont(new java.awt.Font("Sitka Text", 1, 12)); // NOI18N
        back.setText("Back");
        back.setBorder(null);
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(accessories)
                            .addComponent(bagsandpurses)
                            .addComponent(scarvesandcaps)
                            .addComponent(watches)
                            .addComponent(glasses)
                            .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(clothings)
                            .addComponent(dresses)
                            .addComponent(tshirtsandblouses)
                            .addComponent(hoodies)
                            .addComponent(jeansandtrousers)
                            .addComponent(shorts))
                        .addGap(50, 50, 50)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sneakers)
                            .addComponent(slippers)
                            .addComponent(shoes)
                            .addComponent(heels)
                            .addComponent(socks)))
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(skirts)
                        .addGap(251, 251, 251)))
                .addGap(53, 53, 53))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(WomenFashion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(139, 139, 139))
        );
        jPanelLayout.setVerticalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(WomenFashion, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addComponent(accessories, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bagsandpurses, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(glasses, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(scarvesandcaps, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(watches, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(clothings, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(shoes, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dresses, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(heels, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tshirtsandblouses, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(slippers, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(hoodies, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sneakers, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jeansandtrousers, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(socks, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(shorts, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(skirts, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 370, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bagsandpursesLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bagsandpursesLabelMouseEntered
        evt.getComponent().setForeground(java.awt.Color.WHITE);
    }//GEN-LAST:event_bagsandpursesLabelMouseEntered

    private void bagsandpursesLabelMouseExit(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bagsandpursesLabelMouseExit
        evt.getComponent().setForeground(java.awt.Color.BLACK);
    }//GEN-LAST:event_bagsandpursesLabelMouseExit

    private void glassesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_glassesMouseEntered
        evt.getComponent().setForeground(java.awt.Color.WHITE);
    }//GEN-LAST:event_glassesMouseEntered

    private void glassesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_glassesMouseExited
        evt.getComponent().setForeground(java.awt.Color.BLACK);
    }//GEN-LAST:event_glassesMouseExited

    private void scarvesandcapsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_scarvesandcapsMouseEntered
        evt.getComponent().setForeground(java.awt.Color.WHITE);
    }//GEN-LAST:event_scarvesandcapsMouseEntered

    private void scarvesandcapsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_scarvesandcapsMouseExited
        evt.getComponent().setForeground(java.awt.Color.BLACK);
    }//GEN-LAST:event_scarvesandcapsMouseExited

    private void watchesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_watchesMouseEntered
        evt.getComponent().setForeground(java.awt.Color.WHITE);
    }//GEN-LAST:event_watchesMouseEntered

    private void watchesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_watchesMouseExited
        evt.getComponent().setForeground(java.awt.Color.BLACK);
    }//GEN-LAST:event_watchesMouseExited

    private void dressesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dressesMouseEntered
        evt.getComponent().setForeground(java.awt.Color.WHITE);
    }//GEN-LAST:event_dressesMouseEntered

    private void dressesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dressesMouseExited
        evt.getComponent().setForeground(java.awt.Color.BLACK);
    }//GEN-LAST:event_dressesMouseExited

    private void jeansandtrousersMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jeansandtrousersMouseEntered
        evt.getComponent().setForeground(java.awt.Color.WHITE);
    }//GEN-LAST:event_jeansandtrousersMouseEntered

    private void jeansandtrousersMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jeansandtrousersMouseExited
        evt.getComponent().setForeground(java.awt.Color.BLACK);
    }//GEN-LAST:event_jeansandtrousersMouseExited

    private void tshirtsandblousesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tshirtsandblousesMouseEntered
        evt.getComponent().setForeground(java.awt.Color.WHITE);
    }//GEN-LAST:event_tshirtsandblousesMouseEntered

    private void tshirtsandblousesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tshirtsandblousesMouseExited
        evt.getComponent().setForeground(java.awt.Color.BLACK);
    }//GEN-LAST:event_tshirtsandblousesMouseExited

    private void hoodiesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hoodiesMouseEntered
        evt.getComponent().setForeground(java.awt.Color.WHITE);
    }//GEN-LAST:event_hoodiesMouseEntered

    private void hoodiesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hoodiesMouseExited
        evt.getComponent().setForeground(java.awt.Color.BLACK);
    }//GEN-LAST:event_hoodiesMouseExited

    private void shortsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_shortsMouseEntered
        evt.getComponent().setForeground(java.awt.Color.WHITE);
    }//GEN-LAST:event_shortsMouseEntered

    private void shortsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_shortsMouseExited
        evt.getComponent().setForeground(java.awt.Color.BLACK);
    }//GEN-LAST:event_shortsMouseExited

    private void skirtsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_skirtsMouseEntered
        evt.getComponent().setForeground(java.awt.Color.WHITE);
    }//GEN-LAST:event_skirtsMouseEntered

    private void skirtsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_skirtsMouseExited
        evt.getComponent().setForeground(java.awt.Color.BLACK);
    }//GEN-LAST:event_skirtsMouseExited

    private void heelsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_heelsMouseEntered
        evt.getComponent().setForeground(java.awt.Color.WHITE);
    }//GEN-LAST:event_heelsMouseEntered

    private void heelsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_heelsMouseExited
        evt.getComponent().setForeground(java.awt.Color.BLACK);
    }//GEN-LAST:event_heelsMouseExited

    private void slippersMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_slippersMouseEntered
        evt.getComponent().setForeground(java.awt.Color.WHITE);
    }//GEN-LAST:event_slippersMouseEntered

    private void slippersMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_slippersMouseExited
        evt.getComponent().setForeground(java.awt.Color.BLACK);
    }//GEN-LAST:event_slippersMouseExited

    private void sneakersMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sneakersMouseEntered
        evt.getComponent().setForeground(java.awt.Color.WHITE);
    }//GEN-LAST:event_sneakersMouseEntered

    private void sneakersMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sneakersMouseExited
        evt.getComponent().setForeground(java.awt.Color.BLACK);
    }//GEN-LAST:event_sneakersMouseExited

    private void socksMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_socksMouseExited
        evt.getComponent().setForeground(java.awt.Color.BLACK);
    }//GEN-LAST:event_socksMouseExited

    private void socksMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_socksMouseEntered
        evt.getComponent().setForeground(java.awt.Color.WHITE);
    }//GEN-LAST:event_socksMouseEntered

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        WomenFashion p1 = new WomenFashion();
        ChooseGender p2 = new ChooseGender();
        p2.setVisible(true);
        p1.setVisible(false);
        dispose();
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WomenFashion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WomenFashion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WomenFashion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WomenFashion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WomenFashion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel WomenFashion;
    private javax.swing.JLabel accessories;
    private javax.swing.JButton back;
    private javax.swing.JLabel bagsandpurses;
    private javax.swing.JLabel clothings;
    private javax.swing.JLabel dresses;
    private javax.swing.JLabel glasses;
    private javax.swing.JLabel heels;
    private javax.swing.JLabel hoodies;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel;
    private javax.swing.JLabel jeansandtrousers;
    private javax.swing.JLabel scarvesandcaps;
    private javax.swing.JLabel shoes;
    private javax.swing.JLabel shorts;
    private javax.swing.JLabel skirts;
    private javax.swing.JLabel slippers;
    private javax.swing.JLabel sneakers;
    private javax.swing.JLabel socks;
    private javax.swing.JLabel tshirtsandblouses;
    private javax.swing.JLabel watches;
    // End of variables declaration//GEN-END:variables
}
